cities:
  - name: Sevilla
    latitude: 37.3886
    longitude: -5.9823
    elevation: 7
    region: Andalucia
  - name: Malaga
    latitude: 36.7213
    longitude: -4.4217
    elevation: 11
    region: Andalucia
  - name: Cordoba
    latitude: 37.8882
    longitude: -4.7794
    elevation: 106
    region: Andalucia
  - name: Granada
    latitude: 37.1773
    longitude: -3.5986
    elevation: 738
    region: Andalucia
  - name: Almeria
    latitude: 36.8340
    longitude: -2.4637
    elevation: 21
    region: Andalucia
  - name: Cadiz
    latitude: 36.5163
    longitude: -6.2994
    elevation: 6
    region: Andalucia
  - name: Huelva
    latitude: 37.2614
    longitude: -6.9447
    elevation: 54
    region: Andalucia
  - name: Jaen
    latitude: 37.7796
    longitude: -3.7849
    elevation: 573
    region: Andalucia
  - name: Barcelona
    latitude: 41.3874
    longitude: 2.1686
    elevation: 12
    region: Cataluña
  - name: Girona
    latitude: 41.9794
    longitude: 2.8214
    elevation: 70
    region: Cataluña
  - name: Lleida
    latitude: 41.6176
    longitude: 0.6200
    elevation: 199
    region: Cataluña
  - name: Tarragona
    latitude: 41.1189
    longitude: 1.2445
    elevation: 70
    region: Cataluña
  - name: Manresa
    latitude: 41.7282
    longitude: 1.8239
    elevation: 238
    region: Cataluña
  - name: Reus
    latitude: 41.1561
    longitude: 1.1069
    elevation: 117
    region: Cataluña
  - name: Figueres
    latitude: 42.2672
    longitude: 2.9617
    elevation: 39
    region: Cataluña
  - name: Vic
    latitude: 41.9301
    longitude: 2.2549
    elevation: 484
    region: Cataluña
start_date: "2020-01-01"
end_date: "2024-12-31"
